# Generated by Django 5.0.1 on 2024-01-22 10:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='workflow',
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to='core.workflow'),
            preserve_default=False,
        ),
    ]
