# Generated by Django 5.0.1 on 2024-01-23 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_step_workflow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_set', to='core.workflow'),
        ),
    ]
