# Generated by Django 5.0.1 on 2024-01-27 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_step_workflow'),
        ('vacation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requests',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='requests',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='requestshistory',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='requestshistory',
            name='object_id',
        ),
        migrations.AddField(
            model_name='requests',
            name='leave',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vacation.leave'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requestshistory',
            name='leave',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='vacation.leave'),
            preserve_default=False,
        ),
    ]
