# Generated by Django 5.0.1 on 2024-01-27 11:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_requests_status_alter_requestshistory_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestshistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requestshistory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
