# Generated by Django 5.0.1 on 2024-01-30 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_requestshistory_created_at_and_more'),
        ('vacation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='leave',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_set', to='vacation.leave'),
        ),
        migrations.AlterField(
            model_name='requests',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_set', to='core.step'),
        ),
        migrations.AlterField(
            model_name='requests',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_set', to='core.workflow'),
        ),
    ]
