# Generated by Django 5.0.1 on 2024-01-30 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_requests_leave_alter_requests_step_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RequestsHistory',
        ),
    ]
