# Generated by Django 5.0.1 on 2024-01-30 09:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_delete_requestshistory'),
        ('vacation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestsHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('desc', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('next', 'Next'), ('reject', 'Reject'), ('accept', 'Accept')], default='pending')),
                ('reason', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('leave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacation.leave')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.step')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.workflow')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
