# Generated by Django 5.0.1 on 2024-01-30 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_requestshistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestshistory',
            name='request_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
